### ISSUE TITLE
Orca.pet's certificate is "not signed by known authorities or invalid"

### ISSUE THREAD

**Issue by T145** [socram8888/not-on-my-shift#11] opened 2021-09-30 04:34 UTC
I'm trying to download a text file from the site, and am getting this error:
https://github.com/T145/black-mirror/blob/dd72b16aaa32a13332cf0b859fde4becfe59e740/logs/aria2.log#L100

I've tried performing this fix:
https://github.com/aria2/aria2/issues/1636#issuecomment-790042543

But the error persists. `cURL` does not work either.

Personally, I'd feel much more safe if the lists were uploaded to GitHub releases rather than your website.
It's very transparent and easy to configure through GitHub Actions.

**Comment by socram8888** [comment] 2021-09-30 10:28
This is caused by your machine not trusting the new LetsEncrypt ISRG Root X1 CA: https://letsencrypt.org/2020/11/06/own-two-feet.html

Please add it to your system, or update your OS, and try again.

I prefer to have it hosted in my own server, which gives me more freedom in how I build and publish the block lists.

**Comment by T145** [comment] 2021-09-30 18:26
Ubuntu should already support Let's Encrypt. Granted, this started happening right when I swapped GitHub Actions to using a custom Docker image, but even on a fresh Ubuntu install the error persists across every file download utility.

Luckily `wget` gives a more blunt prompt:
```
# wget https://orca.pet/notonmyshift/domains.txt
--2021-09-30 18:17:29--  https://orca.pet/notonmyshift/domains.txt
Resolving orca.pet (orca.pet)... <ip>, <ipv6>
Connecting to orca.pet (orca.pet)|<ip>|:443... connected.
ERROR: The certificate of 'orca.pet' is not trusted.
ERROR: The certificate of 'orca.pet' has expired.
```
On Windows, the prompt from a fresh `wget` install is `Unable to establish SSL connection.`

**Comment by socram8888** [comment] 2021-09-30 19:50
Alright, there's something strange going on. If I enter to https://orca.pet, I get a certificate signed by the ISRG. **But** running `s_client` I get:
```
~$ openssl s_client -servername orca.pet -connect orca.pet:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:1
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
notAfter=Sep 30 14:01:15 2021 GMT
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify error:num=10:certificate has expired
notAfter=Sep 29 19:21:40 2021 GMT
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
notAfter=Sep 29 19:21:40 2021 GMT
verify return:1
depth=0 CN = orca.pet
notAfter=Oct 14 23:57:37 2021 GMT
verify return:1
---
Certificate chain
 0 s:CN = orca.pet
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```
This is slightly hard to debug given this is a OVH hosting and thus I don't have access to the underlying OS, but I'll try some things to fix this ASAP.

**Comment by socram8888** [comment] 2021-09-30 20:11
https://twitter.com/Scott_Helme/status/1443593011393282053 several web services affected. I've tried renewing the certificate from the management panel, if that doesn't work I'll contact support.

**Comment by socram8888** [comment] 2021-09-30 20:24
Seems that requesting the certificate update fixed the issue. Closing.

**Closed by socram8888** 2021-09-30 20:24 UTC
